### ISSUE TITLE
**Create Python Notebooks**

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#1]
To actually advertise this as a full-on receiver function package, and make people use it as well, I don't think we're gonna get around this one!

- [x] Data collection
- [x] Plotting 
    - [x] Single RF
    - [x] RF section
    - [x] Baz/rayp
    - [x] SingleStationStack
- [x] CCP

**Post Notebook things**

- [ ] Somehow host Notebooks for easy use.
    - Create link to an open space such as Google Colab/Binder to host Notebooks that can be opened by anyone 
    - OR simple tell people to open the notebooks from an example directory in the repo through colab or something else.

**Comment by PeterMakus** [comment]
I am creating a second line of tutorial notebooks that work with *hdf5* and *S receiver functions* with the whole `ỲP` network. Just to illustrate some more options. It's also shipping with a ``YAML``config file.
