### ISSUE TITLE
Multiprocessing issues -- macOS?

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#101]
See line 9

Don't know what's happening, @PeterMakus. You coded up the test, have you encountered this before?

```python
 1src/pyglimer/utils/log.py:75: in create_mpi_logger
 2    return start_logger_if_necessary(name, fn, lvl)
 3src/pyglimer/utils/log.py:43: in start_logger_if_necessary
 4    fh = logging.FileHandler(logfile, mode='w')
 5../../../../../anaconda3/envs/pyglimer/lib/python3.8/logging/__init__.py:1147: in __init__
 6    StreamHandler.__init__(self, self._open())
 7_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  
 8_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
 9
12    def _open(self):
13        """
14        Open the current base file with the (original) mode and encoding.
15        Return the resulting stream.
16        """
17>       return open(self.baseFilename, self.mode, encoding=self.encoding)
18E       PermissionError: [Errno 1] Operation not permitted: '/dev/nullrank010.log'
19
20../../../../../anaconda3/envs/pyglimer/lib/python3.8/logging/__init__.py:1176: PermissionError
```

**Comment by lsawade** [comment]
haven't merged most recent dev update... will check if checks pass and close after...

**Comment by lsawade** [comment]
I'm pretty sure the problems I'm having are related to `multiprocessing` launches. Testing on linux now.

**Comment by lsawade** [comment]
Ok, so this is a macOS+multiprocessing issue: [runtime error](https://stackoverflow.com/questions/60691363/runtimeerrorfreeze-support-on-mac)

Figured it out, but makes the example really ugly.

**Comment by PeterMakus** [comment]
Could it be that you just executed the test as

```bash
pytest tests
```

?

If so, try the following (this is what our GH actions do):

```bash
pytest -p no:logging tests
```

The reason for this is that pytest automatically reconfigures logging, which makes the logging tests fail. I am not sure if this is the same issue.

**Comment by lsawade** [comment]
That was it, actually!
