### ISSUE TITLE
Parallel questions/remarks

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#104]
```python
def preprocess(
    phase: str, rot: str, pol: str, taper_perc: float,
    event_cat: obspy.Catalog, model: obspy.taup.TauPyModel,
    taper_type: str, tz: int, ta: int, statloc: str, rawloc: str,
    preproloc: str, rfloc: str, deconmeth: str, hc_filt: float or None,
    saveasdf: bool = False, netrestr=None, statrestr=None,
        client: str = 'joblib'):

    ...

    # Number of cores is usally a power of 2 (therefore 128)
    n_split = int(np.ceil(event_cat.count()/128))
```

Hi @PeterMakus, how much have you played around with this line? Is there a good reason for not using a smaller number than the actual physical core count? Say,

```python
nsplit = psutil.cpu_count(logical=False) - 2
```

The reason why I'm asking is, that if you launch 128 data transfers instead of a maybe 4 you have a bunch of overhead. For 20 traces there is a lot of unnecessary overhead. For the a small database (in example), setting the chunk size gives you a gigantic performance boost. 

Another thing, `n_jobs=-1` always uses the maximum number of available cores. That works sometimes, but not always. For some job schedulers (e.g. LSF) you will have to reset `cpu_affinity` because they are not making all cores available if running a single task with many cores (https://github.com/lwsspy/lwsspy/blob/main/src/lwsspy/utils/reset_cpu_affinity.py). At that point one should probably switch to MPI anyways.

One more thing, but maybe you are aware of this. In the backend, `numpy` and `scipy` use `OMP` to parallelize things using multiple cores and threads. Whenever you parallel compute things using mpi and/or multiprocessing, make sure you set
```bash
export OMP_NUM_THREADS=1
```
otherwise, the different processes will fight over threads and cores in the background.

**Comment by PeterMakus** [comment]
I think you misunderstood something here.

```python
nsplit = psutil.cpu_count(logical=False) - 2
n_split = int(np.ceil(event_cat.count()/128))
```

This will send chunks of 128 traces to be processed by one thread. Depending on how many traces there are, the number of chunks will be determined. (I realised that my comment in the code doesn't make any sense). A number that is too small, will result in slow processing (there is an optimal chunk size, I determined 128 by trial-and-error).

I dare say that there is basically no real example, in which you will only process 20 traces. However, if you can come up with a smart & dynamic way of determining the chunk size, feel free to do so.


Considering `n_jobs`, I wasn't aware of that. BUt I am open to change the code there.

`OMP` I am aware of this, but actually wasn't when I wrote the PyGLImER code here. A way of setting this in python would be:

```python
import os
os.environ['OPENBLAS_NUM_THREADS'] = '1'
import numpy as np
```

Note that this has to be executed before importing numpy or scipy.

**Comment by PeterMakus** [comment]
Yes, I agree. Being able to set the processing to single core, will also allow for better debugging!
