### ISSUE TITLE
MPI run bug in `download_small_db`

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#105]
https://github.com/PyGLImER/PyGLImER/blob/7bb41392c44c1a7aa4c276ee49495466e23d4eff/src/pyglimer/waveform/preprocess.py#L167

Since there is no variable `out` is defined in the `mpi` branch of the conditional statement the function fails after preprocessing a single set of events. Since writing is happening outside of the branch I assume something is missing in the `mpi` branch like `comm.gather`?

Maybe I'm misunderstanding how to run this, but even `mpiexec -c 1 python DataCollectionSAC.py` fails.

**Comment by PeterMakus** [comment]
Will take a look at this!

**Comment by PeterMakus** [comment]
Hey, it works for me. I just do ``mpirun -n N python DataCollectionSAC.py``

**Comment by PeterMakus** [comment]
Note that the figures will be plotted N times, but that probably doesn't matter too much as I assume you will run this in a single core anyways?

**Comment by lsawade** [comment]
Yes exactly. So the example should not be run with MPI, unless you comment out the plotting routines.

**Comment by PeterMakus** [comment]
As I see, this works now, doesn't it? Feel free to reopen if there should still be an issue
