### ISSUE TITLE
Slow download_small_db and fix

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#115]
Hi Peter,

On Friday, I figured out why the small database download is taking so incredibly long. It's a three parter.

1. For a multistation array (still small), the request that was created got pretty large. E.g., YP has 125 station * 2000 events in a 2 year time span, *(number of possible channels) LH and BH, *(number of possible locations) 00, 01. With such a large request the FDSN request sometime takes a while to respond. Longer than what Obspy's Client allows. My first attempt was to just chunk it up, which worked, but was only a third of the story.
2. The network-station-event loop to determine the `toa` is expensive.
3. The second problem was the writing of ASDF files. For each trace(!) the write_ds function, opened and closed the `ASDFDataset`. That was an incredible overhead for tens of thousands of traces.

Plan is to:

1. [x] Split up the `compute_toa` loop by into `<network>.<station>` so that each station can be checked separately in parallel using `Parallel()` and `delayed()`.
2. [x] This makes it also easier to write ASDF files, since you can request the data for each station separately and open the `ASDFDataset` once and write all traces.
3. [x] I plan on implementing a switch, so that when only one station is requested, the `compute_toa` loop splits the events.

I haven't put in a pull request yet since it's still a bit messy. But I will clean up some time this week.

**Comment by PeterMakus** [comment]
That sounds good. I don't know why I implemented it to write every trace.
I do remember though that I was thinking that the FDSN thing could be an issue, but for some reason I didn't fix it back then.

Concerning the writing: We should find a good compromise between avoiding data loss (i.e., save the data at least a couple of times in the process, so not all is lost if something crashes or the process is interrupted) and time it takes to save the data

**Comment by lsawade** [comment]
### Update

So, I have now changed the download function away from ASDFDataSet to the custom HDF5 solution for our raw files. It seems to work with at least the same speed if not faster. 

I will address the last task, "splitting the events", in the coming days.

Finally, the processing and the CCP stacking have to be changed to read the new style database.

**Comment by PeterMakus** [comment]
I already adopted the processing in an earlier commit (feel free to test it) and the CCP stacking should not need to be changed as it does not access the `RawDatabase` at all but only `RFDataBase`, so I think we are almost set.

**Comment by PeterMakus** [comment]
Excellent! Yes, that is something I was technically aware of but have never thought of as a problem in the context of this implementation.
Am I correct in assuming that all of this only affects `download_small_db` but not the `MassDownloader` functions?

As for the `__check_times_small_db_sub()`, will it still request data if only one or two channels are missing? That can actually happen sometimes due to unreliable availability of other channels. Also brings me to a completely different issue: Do we have any kind of mechanism that checks whether a station does actually have three channels or do we also download, e.g., geofon data?

**Comment by lsawade** [comment]
> Am I correct in assuming that all of this only affects `download_small_db` but not the `MassDownloader` functions?

Yes, the `MassDownloader` should handle all of this (I think)

> As for the `__check_times_small_db_sub()`, will it still request data if only one or two channels are missing? 

Right now, yes. The behavior could be changed though and it is very simple to even allow for a customization here. E.g. download if only one of three channels is available vs. download only if all three are unavailable.

> Also brings me to a completely different issue: Do we have any kind of mechanism that checks whether a station does actually have three channels or do we also download, e.g., geofon data?

In download_small_db, we are not performing this test. But a check for availability could be done. I'm already creating a dictionary that has `network.station.channel` structure checking whether a certain station has 3 components becomes involved in the sense that, `download_small_db` takes in a channel string like `BH*` or `*H*`. Then, checking whether a specific channel type contains 3 components, can be done, but the function is also rather elaborate.

---

Another check that we should do in `__check_times_small_db_sub()` is whether 
an event is actually within the timeframe of the stations active time. And skip the event if it is outside. That way many requests can be omitted.

**Comment by lsawade** [comment]
> - [ ] I plan on implementing a switch, so that when only one station is requested, the compute_toa loop splits the events.

This is harder than I expected, because it requires a different way of implementing the `wave_in_hdf5()` function. Due to possible race condition, because both try to access and/or write av_data. I need a different way of checking the available data in the HDF5 file. 

I originally started tinkering on this function because it took forever to download all data related to HRV due to the compute_toa loop which is not parallel. I think I should really implement this, but it will require a separate subsubfunction. :<

**Comment by lsawade** [comment]
This is done.
