### ISSUE TITLE
pyvista -- missing libEGL.so.1 in headless pytest

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#117]
Issue opened at https://github.com/pyvista/pyvista/issues/3175

https://github.com/pyvista/pyvista/issues/2142 and https://github.com/pyvista/pyvista/pull/2151

**Comment by PeterMakus** [comment]
This does not seem to be a problem any more. The last tests didn't fail. We can reopen if the issue occurs again.

**Comment by lsawade** [comment]
Closed issue https://github.com/pyvista/pyvista/issues/3175 as well
