### ISSUE TITLE
Change way velocity model is loaded

### ISSUE THREAD

**Issue by lsawade** [PyGLImER/PyGLImER#14]
I think it be nice to have a standard model for `RFStream.moveout()`. Basically set it up like 

```python
def load_model(fname='iasp91', ...):
    # Get standard model
    if vmodel == 'iasp91':   
        # Something like
        fname = os.path.join(os.path.dir(os.path.dir(__file__)), "data", "velocity_model", "iasp91.data")
    else:
        fname = vmodel
    ...
```

The details should be reworked by you Peter, since I'm note quite following the `_MODEL_CACHE= {}`, we can discuss this at some point.

To facilitate this, the velocity model must become part of the package meaning. the `pyglimer` directory needs a subdirectory `data` in which `iasp91.dat` would be located.

Additionally, the file needs to be included in the `package_data` argument in `setup.py` for correct distribution and installation. As:

```python
setup(
    ...,
    package_data={
            'pyglimer': ['data/velocity_models/iaps91.dat']
        },
    ...
)
```

I would however advise against putting GyPSuM there since it's fairly large in size. But, whatever floats your boat. That way you don't have to think about people having to download the velocity model the package using PyPi or not.

---

<strike>***Current Workaround:***

For the `example`  folder before doing anything that has to do with the velocity model, I wrap the function using a decorator. I'm changing the working directory and then changing it back. Not very elegant, but it does the job.

```python
import os
from pyglimer import RFStream 

def chdir(func, rpath=".."):
    def wrapper_chdir(*args, **kwargs):
        
        # Get dir
        cw = os.path.abspath(os.getcwd())
        print(os.path.abspath(os.getcwd()))        
        # Change dir
        os.chdir(os.path.join(cw, rpath))
        print(os.path.abspath(os.getcwd()))
        
        # Exectute function
        func(*args, **kwargs)
        
        # Change back
        os.chdir(cw)
        print(os.path.abspath(os.getcwd()))
        
    return wrapper_chdir

rfst.moveout = chdir(rfst.moveout)
rfst.moveout(rfst, "iasp91.dat")
```
</strike>

Doesn't work because it's a method of a class and self is hard to assign...

**Comment by PeterMakus** [comment]
Zombie issue. I think we took care of this long ago...
