### ISSUE TITLE
Bootstrap

### ISSUE THREAD

**Issue by PeterMakus** [PyGLImER/PyGLImER#28]
Add a bootstrap method for CCP and single station stacks.

**Comment by PeterMakus** [comment]
Alright, I decided to implement that in form of *Monte Carlo Case Resampling*.
Will start out by implementing this for single station stacks and see, whether it's sensible to do for CCP stacks as well. A viable and less expensive method would be *jack knife* (albeit slightly less precise).

**Comment by PeterMakus** [comment]
![output_test](https://user-images.githubusercontent.com/47005330/134921260-e9b8158b-b087-4c86-93d2-35b48eb4c5ba.png)

Ok, standard deviation for a PRF single station stack, see above. That's now implemented in the dev branch. Also, a little howto in the single station stack jupyter notebook

**Comment by lsawade** [comment]
Alrighty, the trick here should be working with an identity of the Variance: [Variance Wiki](https://en.wikipedia.org/wiki/Variance#Definition)

We are already saving a sum of RF elements at point X. To compute the variance we simply have to save the sum of RF ^2

See following example:

```python

import numpy as np

# Make random sampling at depth
x = np.random.rand(1000)

s = np.sum(x)
s2 = np.sum(x**2)

v = s2/x.size - (s/x.size)**2
np.isclose(v, np.var(x))

>>> True

```

**Comment by PeterMakus** [comment]
I think we agreed that it's not super useful to go beyond what we've already done.
