### ISSUE TITLE
gctrack function fails sporadically

### ISSUE THREAD

**Issue by PeterMakus** [PyGLImER/PyGLImER#55]
@lsawade I noticed that the unittest for gctrack (in `geo_utils`) has a tendency to fail (I use randomized values, so that's only sometimes the case. The test is in `tests/test_geoutils` could you have a look and see if it's a problem with my test? 

Cheers

**Comment by lsawade** [comment]
I haven't noticed this, let me take a look. I have been using it myself quite heavily for my source inversion project and have not noticed this behavior!

**Comment by lsawade** [comment]
Seems to have something to do when ±180 degrees is crossed and the epicentral distance is very close to 180. 
Do we need capability beyond 180 deg epicentral distance? Otherwiese a ValueError raise could do the trick.

**Comment by lsawade** [comment]
To things I have figured out, accuracy increases using smaller steps. The `reckon` algorithm I wrote is not very accurate and should be taken with a grain of salt. That being said, as long as d is chosen small enough it is fine for our purposes. We are only using it to compute GCTracks for the cross sections. Since it's fast it's fine. Let me know what you think.

```python
# Slightly better accuracy, but not great...
trackdists = np.linspace(0, dists[_i], int(np.ceil((dists[_i])/dist)))
track = np.array(reckon(lat[_i], lon[_i], trackdists, az[_i]))
```

**Comment by lsawade** [comment]
Sure!

**Comment by lsawade** [comment]
Test is implemented like so:


```python 
# Least distance between waypoints
mind = 10

# Create random new distance ranging from 
# 0.5-1.0 * (a hundreth of the least distance betweem waypoints)
d = (0.5 * np.random.rand(1) + 0.5)*mind/100

# Create randomly but evenly distributed waypoints.
lon, lat = e2D(10, 340, 160, mind)

# Compute GCTrack
qlat, qlon, qdists, sdists = gu.gctrack(lat, lon, d)

```

**Comment by PeterMakus** [comment]
Can this be closed?
