### ISSUE TITLE
Feed in offline data

### ISSUE THREAD

**Issue by PeterMakus** [PyGLImER/PyGLImER#78]
Feature to use waveform data that is not available on FDSN servers.

**Comment by lsawade** [comment]
I have access to the data now, will reshape to correct format!

**Comment by PeterMakus** [comment]
Ok changed my mind a little, this is how it will be solved:

PyGLImER get's a function, which takes 1. a `Generator` function as input. This generator has to yield (1) obspy streams (2) the associated station coordinates (response will not be removed) or a full obspy inventory (response will be removed if available).

The advantage with this approach are:
1. If the headers of the data are incomplete/faulty, it will be easier for the user to take care of the problem.
2. Additional flexibility in terms of data structure (i.e., they don't need to follow a specific directory structure).

**Comment by PeterMakus** [comment]
Fully implemented in #8c81b15 in `dev` branch. Feature will come with the next release.
